- hosts: all
  tasks:
    - name: Add the user 'ubuntu' with a primary group of 'admin'
      user:
        name: ubuntu
        groups: admin
        append: yes
    - name: PKI | get pubkey from Github and placed as authorized_keys
      get_url:
       url: https://github.com/{{ item }}.keys
       dest: /tmp/{{ item }}.keys
      with_items:
        - karantan
    - name: PKI | Ensure .ssh/ folder exists
      file:
        owner: ubuntu
        group: ubuntu
        path: /home/ubuntu/.ssh/
        state: directory

    - name: PKI | Add downloaded keys to authorized_keys
      assemble:
        dest: /home/ubuntu/.ssh/authorized_keys
        src: /tmp
        regexp: \.keys$
        owner: ubuntu
        group: ubuntu

    - name: PKI | Disallow password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^(#)?(\\s)?PasswordAuthentication (yes|no)$"
        line: PasswordAuthentication no

    - name: Restart sshd
      action: service name=ssh state=restarted
